#更新fork
name: My update fork

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/my-auto-fork.yml'
  workflow_dispatch: 
  schedule:
    - cron: '0 16 * * *' #0点定时任务

jobs:
  build:
    runs-on: ubuntu-latest
    # if: ${{ github.event.repository.owner.id == github.event.sender.id && github.actor != 'gedoor' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set env
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"

        # 设置上游仓库变量
        upstream_repository="gedoor/legado"
        echo "upstream_repository=$upstream_repository" >> $GITHUB_ENV

    - name: Update fork
      continue-on-error: true
      run: |
        git_pull_ok="false"
        echo "git_pull_ok=$git_pull_ok" >> $GITHUB_ENV

        # git remote add upstream https://github.com/gedoor/legado.git
        # git remote -v
        # git fetch upstream
        # # git checkout master
        # # git merge upstream/master
        # # git pull upstream master --rebase
        # git merge-base refs/heads/master refs/remotes/upstream/master
        # git push origin master

        sed -i "s#${{ github.repository }}#${{ env.upstream_repository }}#g" .git/config
        git fetch
        git pull --rebase
        sed -i "s#${{ env.upstream_repository }}#${{ github.repository }}#g" .git/config
        git pull --rebase
        git push
        
        echo "git push ...."
        git_pull_ok="true"
        echo "git_pull_ok=$git_pull_ok" >> $GITHUB_ENV

    - name: Dispatches Action
      continue-on-error: true
      if: startsWith(env.git_pull_ok,'true')
      run: |
        curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/my-test.yml/dispatches \
            -d '{"ref":"refs/heads/master","inputs":{}}' 

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 5
        keep_minimum_runs: 2

